### ISSUE TITLE
no border

### ISSUE THREAD

**Issue by jan4984** [ricmoo/QRCode#6]
no white border for rows, and lot's scanner can not find the generated qrcode.

**Comment by ricmoo** [comment]
The "quiet zone" does need to be added manually, and should be 4 modules wide.

The library does not do this because it is easy for the calling library to do itself, is not always required (often a display on a device already has a valid quiet zone, or printed on paper which is already white) and adds memory requirements for data that does not need to be encoded (since it is known to be padding).

If you look at the [Firefly Source Code](https://github.com/firefly/wallet/blob/master/source/firefly/firefly_display.cpp#L411), you can see how we manually add the 3 pixels (although it should be 8 pixels, since each module is 2 pixels, but there is not room on the display) of quiet zone around the QR code.

If you need help adding the quiet zone, let me know what your target is and we will see if we can help. :)

**Comment by jan4984** [comment]
That's right. Thanks Ricmoo.
