### ISSUE TITLE
memory out of range question

### ISSUE THREAD

**Issue by fawdlstty** [ricmoo/QRCode#7]
Hi friend, in line:

https://github.com/ricmoo/QRCode/blob/master/src/qrcode.c#L709

after this code, some code access the variable but out of range: [0, data->capacityBytes)  .if i fix the error, the code likes uint8_t *result = new uint8_t [data->capacityBytes * 100];

after fix, i have generate image, but it can't scan from any qrcode app.such as:

![text](https://user-images.githubusercontent.com/7323999/55800362-275f5000-5b06-11e9-80c1-303e76bf2b7f.png)

ide: visual studio 2017

**Comment by ricmoo** [comment]
Can you include your code you use to generate the at code? You shouldn’t need to touch any parts of the data structure directly...

**Comment by fawdlstty** [comment]
I just include qrcode.c and rename qrcode.cpp and modify that code `uint8_t result [data->capacityBytes];`

because Visual C++ does not support the grammar.

**Comment by ricmoo** [comment]
The syntax should certainly be supported, it is just creating a variable on the stack.

If you add a `new` to that line, you are allocating space on the heap, which will leak memory and could certainly cause corruption depending on how you use it, where `free` Is called and such.

You can leave it as a .c file, and wrap the header in `extern C` guards, which is a much safer way to modify the code, since all you are doing is changing the name mangling for the functions.

**Comment by fawdlstty** [comment]
![20190411091356](https://user-images.githubusercontent.com/7323999/55923880-2deee400-5c3a-11e9-86de-74256a89da0f.png)
this is source, file is .c, visual studio is not support

**Comment by fawdlstty** [comment]
![20190411091356](https://user-images.githubusercontent.com/7323999/55923940-668ebd80-5c3a-11e9-9592-1bd39aea75a9.png)
this is source, file is .c, visual studio is not support

**Comment by fawdlstty** [comment]
only gcc and clang support

**Comment by fawdlstty** [comment]
![20190411092139](https://user-images.githubusercontent.com/7323999/55924177-4f9c9b00-5c3b-11e9-8ed3-0bd6ca0aa0f2.png)
compile output

**Comment by ooxi** [comment]
Variable length arrays are supported in C99, but not in C++. You can replace the expression with a call to [alloca](http://man7.org/linux/man-pages/man3/alloca.3.html) or [std::array](https://de.cppreference.com/w/cpp/container/array).

While `alloca` might not be available on your platform, `std::array` most likely will. It will however use the heap instead of the stack.

**Comment by fawdlstty** [comment]
> While alloca might not be available on your platform

Using alloca may have an impact on the implementation because it changes the stack layout

> std::vector most likely will. It will however use the heap instead of the stack.

I implemented it as a heap, and the compilation was fine, but the final output of the qr code was invalid

**Comment by ricmoo** [comment]
Right, I don’t really know how to solve this at this point. You are correct,  that the Microsoft compiler cannot handle dynamic stack allocation. I’m curious is a .a file would suffice.

Using alloc is completely outside the purpose of this library though, which is intended to use stack only. The performance and more importantly, the memory safety of using alloc on embedded systems is greatly impacted, where any fragmentation can cause the system to non-deterministically cease to operate. The purpose of this library is to allow a heap-free implementation. There are plenty of existing heap-based implementations though. For example: https://github.com/nayuki/QR-Code-generator

This library is also meant to be C, while std::vector requires a C++ runtime, which adds 500-1400 bytes to the footprint, which would put this library outside of the capacity of many platforms it targets.

Does that make sense?

**Comment by nayuki** [comment]
> There are plenty of existing heap-based implementations though. For example: https://github.com/nayuki/QR-Code-generator

Just for the record: My [C++ library](https://github.com/nayuki/QR-Code-generator/tree/master/cpp) is heap-based because it uses `std::vector`. But my [C library](https://github.com/nayuki/QR-Code-generator/tree/master/c) does not allocate heap memory; instead it requires the user to pass in appropriately sized buffers (which can be allocated on the stack or heap).

You wrote your C library inspired by my C++ library, but then I wrote my own C implementation some months later. This could explain why you might be unaware of my new developments.

**Comment by ricmoo** [comment]
Ah yes, sounds exactly the same then. It makes memory management much more obvious to pass in (and often reuse) a clump of memory, especially in the C world.

Does your library work using the MS compiler? I’ve had a few people have issues with it, and I personally always use GCC or LLVM, but MS is on record saying they have no intentions of ever supporting dynamic stack allocation. :(

For anyone interested in this, certainly check out nayuki’s libraries, which absolutely inspired this library in the first place, and also in general are just well written and cover a diverse set of problems. :)

**Comment by fawdlstty** [comment]
Both libraries are great. Thank you for advice

**Comment by nayuki** [comment]
> Does your library work using the MS compiler?

Unsure, because I can't be bothered to reinstall the 4-gigabyte Visual Studio development environment again. People have reported C++ problems in the past (available in my issues / pull requests), but I think I resolved them by eschewing const fields because they mess up implicit constructor generation. As for C, I use C99 features, and I believe the first Microsoft compiler that fully supports C99 is MSVC++ 2013.

> MS is on record saying they have no intentions of ever supporting dynamic stack allocation

I was unaware they stated this position. That said, I heard that stack allocation is not in the C standard, so it is a vendor extension no matter what. I'm not sure if stack allocation is the same as `alloca()`.

Note that in my library, you declare and use buffers like this:

    // 173 bytes, if we expect no greater than version 5.
    uint8_t qrcode[qrcodegen_BUFFER_LEN_FOR_VERSION(5)];
    
    // 3918 bytes, worst case that covers everything.
    uint8_t tempBuffer[qrcodegen_BUFFER_LEN_MAX];
    
    const char *text = "Hello, world!";
    
    bool ok = qrcodegen_encodeText(
        text,
        tempBuffer,
        qrcode,
        qrcodegen_Ecc_LOW,
        qrcodegen_VERSION_MIN,
        5,  // maxVersion
        qrcodegen_Mask_AUTO,
        true);
    
    if (ok)
        printQr(qrcode);
